/**
 * Supports the Editor window.
 */

import { nativeTheme, BrowserWindow, app } from "electron";
import { TLShotApi } from "./TLShotApi";
import { MainProcessPreferences } from "./MainProcessPreferences";
import { MainProcessQueries, MainProcessStore } from "./MainProcessStore";
import { atom, react } from "signia";
import { waitUntil } from "@/shared/signiaHelpers";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const EDITOR_WEBPACK_ENTRY: string;
declare const EDITOR_PRELOAD_WEBPACK_ENTRY: string;

export class RootWindowService {
  private rootWindow = atom(
    "rootWindow",
    undefined as BrowserWindow | "pending" | undefined
  );

  constructor() {
    react("createRootWindowWhenNeeded", () => {
      if (this.needsRootWindow() && this.rootWindow.value === undefined) {
        void this.upsertRootWindow();
      }
    });

    react("rootWindowLogger", () => {
      console.log("Service/RootWindow", "changed:", this.rootWindow.value);
    });
  }

  needsRootWindow() {
    return MainProcessQueries.hasActivities.value;
  }

  handleRootWindowClose(rootWindow: BrowserWindow) {
    MainProcessPreferences.set(
      "editorWindowDevtools",
      rootWindow.webContents.isDevToolsOpened()
    );
    MainProcessPreferences.set("editorWindowBounds", rootWindow.getBounds());
    MainProcessStore.remove(
      MainProcessQueries.allActivities.value.map((a) => a.id)
    );
    this.rootWindow.set(undefined);
  }

  async upsertRootWindow() {
    if (this.rootWindow.value) {
      return waitUntil("rootWindowAvailable", () =>
        this.rootWindow.value !== "pending" ? this.rootWindow.value : undefined
      );
    }

    this.rootWindow.set("pending");
    try {
      const rootWindow = await this.createRootWindow();
      this.rootWindow.set(rootWindow);
      return rootWindow;
    } catch (error) {
      this.rootWindow.set(undefined);
      throw error;
    }
  }

  async getRootWindow() {
    if (this.rootWindow.value === "pending") {
      return waitUntil("rootWindowAvailable", () =>
        this.rootWindow.value !== "pending" ? this.rootWindow.value : undefined
      );
    }

    return this.rootWindow.value;
  }

  async openDevTools() {
    const rootWindow = await this.upsertRootWindow();
    rootWindow.webContents.openDevTools();
    rootWindow.show();
  }

  private async createRootWindow() {
    if (!app.isReady()) {
      await app.whenReady();
    }

    console.log("RootWindowService: create new root window");
    const isDarkMode =
      nativeTheme.shouldUseDarkColors ||
      nativeTheme.shouldUseInvertedColorScheme;
    const backgroundColor = isDarkMode ? "#212529" : "#f8f9fa";

    // Create the browser window.
    const rootWindow = new BrowserWindow({
      webPreferences: {
        preload: EDITOR_PRELOAD_WEBPACK_ENTRY,
      },
      show: false,
      backgroundColor,
    });

    const prevBounds = MainProcessPreferences.get("editorWindowBounds", {
      width: 1024,
      height: 768,
      x: -1,
      y: -1,
    });

    if (prevBounds.x >= 0 && prevBounds.y >= 0) {
      rootWindow.setBounds(prevBounds);
    } else {
      rootWindow.setSize(prevBounds.width, prevBounds.height);
      rootWindow.center();
    }

    rootWindow.on("close", () => {
      console.log('RootWindowService: "close" event');
      this.handleRootWindowClose(rootWindow);
    });

    rootWindow.on("closed", () => {
      console.log('RootWindowService: "closed" event');
      this.rootWindow.set(undefined);
    });

    // and load the index.html of the app.
    await rootWindow.loadURL(EDITOR_WEBPACK_ENTRY);

    TLShotApi.getInstance().windowDisplayService.handleWindowCreated(
      rootWindow,
      undefined
    );

    // Open the DevTools.
    if (MainProcessPreferences.get("editorWindowDevtools", false)) {
      rootWindow.webContents.openDevTools();
      rootWindow.show();
    }

    return rootWindow;
  }
}
